EZP-29737: Invalid UDW container height after resizing window
ezsystems/ezplatform-admin-ui-modules pull request #108
Opened 2018-10-17 11:26 UTC by sunpietro

https://jira.ez.no/browse/EZP-29737

2018-10-17 11:32 UTC, dew326 approved these changes

2018-10-17 12:11 UTC, tischsoic commented on src/modules/universal-discovery/universal.discovery.module.js
> +        this._refMainContainer = ref;
I would go for `React.createRef()`.

2018-10-17 12:12 UTC, tischsoic commented on src/modules/universal-discovery/universal.discovery.module.js
> +        this._refMainContainer = ref;
I would go for `React.createRef()`.

2018-10-17 12:13 UTC, tischsoic commented on src/modules/universal-discovery/universal.discovery.module.js
> +        this._refMainContainer = ref;
But if we want to stick with this way in order to look it the same as in other places, then OK.

2018-10-17 12:24 UTC, sunpietro commented on src/modules/universal-discovery/universal.discovery.module.js
> +        this._refMainContainer = ref;
I wanted to keep the consistency. If we decide to use `React.createRef()` here and there, then we should change it everywhere in this repository.

2018-10-17 12:33 UTC, tischsoic approved these changes

2018-10-18 09:45 UTC, sunpietro commented
@micszo can you take care of it, or assign someone, please? :)

2018-10-18 09:50 UTC, micszo commented
@sunpietro ok :) could you buff up the description with some steps?

2018-10-18 10:01 UTC, sunpietro commented
@micszo and other QA members: change the browser window height from tall to short and you should notice, that with this fix the buttons at the bottom of UDW don't disappear below the fold anymore.

2018-10-18 10:58 UTC, barbaragr requested changes
When I change height, buttons slide down outside the UDW
[udw_btns.zip](https://github.com/ezsystems/ezplatform-admin-ui-modules/files/2491551/udw_btns.zip)

2018-10-18 11:39 UTC, sunpietro commented
@barbaragr this is expected behaviour, because the container height is updated with a delay, to avoid unneccesary calculations which are really expensive in terms of performance.

2018-10-19 08:38 UTC, barbaragr approved these changes

2018-10-19 08:47 UTC, merged

2018-10-19 08:47 UTC, lserwatka commented
@sunpietro you can merge it up

2018-10-19 08:50 UTC, sunpietro commented
@lserwatka done :)