EZP-29746: Selected item blinking while loading its children in UDW
ezsystems/ezplatform-admin-ui-modules pull request #111
Opened 2018-10-19 09:39 UTC by sunpietro

https://jira.ez.no/browse/EZP-29746

2018-10-19 10:21 UTC, dew326 requested changes

2018-10-19 10:21 UTC, dew326 commented on src/modules/universal-discovery/components/finder/finder.component.js
> +            () => ({ locationsMap: this.locationsMap, activeLocations: this.activeLocations }),
If you created `setPreselectedState` method you can use it here.

2018-10-19 10:21 UTC, dew326 commented on src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
> +                isSelected={selectedContent.find((content) => content.id === location.id)}
`isSelected` suggests it's boolean but is passed content?

2018-10-19 10:23 UTC, sunpietro commented
ping @dew326

2018-10-19 10:30 UTC, dew326 approved these changes

2018-10-23 13:07 UTC, tischsoic commented on src/modules/universal-discovery/components/finder/finder.tree.branch.component.js
> +        const selected = location.id === this.state.selectedItem;
I would go for `selectedLocationId` instead of `selectedItem` because for the former is more descriptive.

2018-10-23 13:07 UTC, tischsoic commented on src/modules/universal-discovery/universal.discovery.module.js
> +                this.setState(() => ({
Why we are setting these state's variables here and not in the first callback? We are waiting for `this.props.cotfAllowedLocations` to change or somehow influence rendering order? I don't understand idea behind it.

2018-10-23 13:07 UTC, tischsoic commented on src/modules/universal-discovery/universal.discovery.module.js
> +                this.setState(() => ({
It seems to me that we want to reset something? Why would we need that?

2018-10-23 13:07 UTC, tischsoic commented on src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
> +            ].join(' '),
👍

2018-10-23 13:07 UTC, tischsoic commented on src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
> +            ].join(' '),
I would go for helper function accepting object `{ 'some-class-name': true | false }`.

2018-10-23 13:32 UTC, micszo commented
@sunpietro looks like it needs a rebase. :)

2018-10-24 08:24 UTC, sunpietro commented on src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
> +            ].join(' '),
I get your point, but we won't do it now.

2018-10-24 08:24 UTC, sunpietro commented
@micszo branch has just been rebased

2018-10-24 12:44 UTC, micszo commented
Follow-up issue https://jira.ez.no/browse/EZP-29759.

2018-10-24 12:46 UTC, micszo approved these changes

2018-10-24 13:06 UTC, merged

2018-10-24 13:07 UTC, lserwatka commented
@sunpietro you can merge it up