EZP-29996: Move CSS files for Universal Discovery Module to Admin UI
ezsystems/ezplatform-admin-ui-modules pull request #130
Opened 2019-01-13 15:27 UTC by sunpietro

https://jira.ez.no/browse/EZP-29996

## THINGS DONE
- [x] moved CSS styles from JS files to SASS files,
- [x] converted icons to use the `Icon` component instead of raw HTML tags,
- [x] corrected colours and sizes,
- [x] corrected clickable elements accessibility in all the UI modules.

2019-01-15 10:02 UTC, dew326 approved these changes

2019-01-15 12:20 UTC, tischsoic requested changes

2019-01-15 12:20 UTC, tischsoic commented on src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
> +        return <Icon name="spinner" extraClasses="ez-spin ez-icon-x2 ez-icon--small ez-icon--light" />;
It might be good time to delete `ez-icon-x2` which is redundant and occurs in several files. But for me it's not deal-breaker. 🙂

2019-01-15 12:20 UTC, tischsoic commented on src/modules/multi-file-upload/components/upload-list/upload.item.component.js
> +                tabIndex="-1"
I don't think we need to set `tabIndex="-1"` for `div`s which are not focusable by default.

2019-01-15 13:00 UTC, tischsoic commented on src/modules/multi-file-upload/components/upload-list/upload.item.component.js
> +                tabIndex="-1"
Me and @dew326 discussed this in private and as Dariusz noted that:
> A negative value (usually tabindex="-1") means that the element should be focusable, but should not be reachable via sequential keyboard navigation. It's mostly useful to create accessible widgets with JavaScript.

source: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

2019-01-15 13:01 UTC, tischsoic approved these changes
`tabIndex="-1"` is OK, so ✅ 🙂

2019-01-17 11:50 UTC, dew326 commented
@micszo changed base branch, rebased with master, fixed issue with UDW. Ready for re-test.

2019-01-17 14:01 UTC, micszo commented
Only Time TCs failed.

2019-01-17 14:24 UTC, micszo approved these changes

2019-01-17 20:13 UTC, merged