EZP-30099: removes short datetime format
ezsystems/ezplatform-admin-ui-modules pull request #142
Opened 2019-02-19 22:19 UTC by pawbuj

jira: https://jira.ez.no/browse/EZP-30099

2019-02-22 10:27 UTC, tischsoic approved these changes

2019-02-22 10:33 UTC, dew326 approved these changes

2019-02-22 14:29 UTC, dew326 requested changes
Looks like it's not valid anymore.

2019-02-25 09:04 UTC, pawbuj commented
requirements were changed

2019-02-25 09:04 UTC, closed without merging