EZP-30346: Broken notifications with html
ezsystems/ezplatform-admin-ui-modules pull request #170
Opened 2019-03-26 16:10 UTC by ViniTou

>Jira : https://jira.ez.no/browse/EZP-30346

Related:
https://github.com/ezsystems/ezplatform-admin-ui/pull/930

2019-03-27 09:06 UTC, dew326 requested changes

2019-03-27 09:06 UTC, dew326 commented on src/modules/sub-items/sub.items.module.js
> +                placeholder: Translator.trans(
I would use a more explanatory key name. What if we will have to add the second placeholder?

2019-03-28 08:40 UTC, ViniTou commented
@dew326 
should look better now.

2019-03-28 08:42 UTC, dew326 approved these changes

2019-03-28 12:37 UTC, tischsoic approved these changes

2019-03-28 12:37 UTC, tischsoic commented on src/modules/sub-items/sub.items.module.js
> +            window.eZ.helpers.notification.showSuccessNotification(message, () => {}, rawPlaceholdersMap);
Nitpick: instead of passing `() => {}` we can pass `null`.

2019-03-28 12:53 UTC, katarzynazawada approved these changes

2019-03-28 12:56 UTC, lserwatka commented
@ViniTou could you rebase?

2019-03-28 13:18 UTC, ViniTou commented
@lserwatka 
done

2019-03-28 13:20 UTC, merged

2019-03-28 13:20 UTC, lserwatka commented
Could you merge it up?