EZP-30413: Long name items are displayed without "..." in UDW
ezsystems/ezplatform-admin-ui-modules pull request #178
Opened 2019-04-09 07:21 UTC by tischsoic

JIRA: https://jira.ez.no/browse/EZP-30413

2019-04-09 07:23 UTC, tischsoic commented on src/modules/universal-discovery/components/finder/finder.tree.leaf.component.js
> +                <span className="c-finder-tree-leaf__content-name">{location.ContentInfo.Content.Name}</span>
Note: ellipsis stopped working after adding `display: flex` on `c-finder-tree-leaf`, so I wrapped content name in `span`.

2019-04-09 07:26 UTC, dew326 approved these changes

2019-04-09 13:20 UTC, barbaragr requested changes
Blue frame around the check button is still visible.

2019-04-11 08:30 UTC, tischsoic commented
I removed select content button outline - ping @barbaragr

2019-04-11 09:07 UTC, barbaragr approved these changes

2019-04-11 09:11 UTC, merged