EZP-30396: Unify bootstrap labels for danger/error
ezsystems/ezplatform-admin-ui-modules pull request #183
Opened 2019-04-17 07:50 UTC by tischsoic

JIRA: https://jira.ez.no/browse/EZP-30396

2019-04-25 12:53 UTC, sunpietro requested changes
I believe we're missing compiled files as well, right?

2019-04-25 13:06 UTC, tischsoic commented
@sunpietro In 3.0 we will no longer compile files and I assumed that it will be merged after https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/181

2019-04-26 09:03 UTC, dew326 approved these changes

2019-05-06 15:06 UTC, sunpietro approved these changes

2019-05-09 13:45 UTC, barbaragr approved these changes

2019-05-13 14:00 UTC, merged