[WIP] EZP-30128: [Follow-up] Fix Sub-items delete/trash actions'  messages
ezsystems/ezplatform-admin-ui-modules pull request #199
Opened 2019-07-19 11:50 UTC by tischsoic

JIRA: https://jira.ez.no/browse/EZP-30128

2019-07-19 11:51 UTC, tischsoic commented on src/modules/sub-items/sub.items.module.js
> +            this.handleBulkOperationFailedNotification(
Only Prettier here.

2019-07-19 11:51 UTC, tischsoic commented on src/modules/sub-items/sub.items.module.js
> +        window.eZ.helpers.notification.showWarningNotification(
Only Prettier here.

2019-07-19 13:41 UTC, SylvainGuittard requested changes

2019-07-19 13:41 UTC, SylvainGuittard commented on Resources/translations/sub_items.en.xliff
> +        <source>Are you sure you want to send to the trash the selected content item(s)?</source>
```suggestion
        <source>Are you sure you want to send to trash the selected content item(s)?</source>
```

2019-07-19 13:41 UTC, SylvainGuittard commented on Resources/translations/sub_items.en.xliff
> +        <target state="new">Are you sure you want to send to the trash the selected content item(s)?</target>
```suggestion
        <target state="new">Are you sure you want to send to trash the selected content item(s)?</target>
```

2019-07-23 06:06 UTC, DominikaK commented on Resources/translations/sub_items.en.xliff
> +        <source>Are you sure you want to send to the trash the selected content item(s)?</source>
```suggestion
        <source>Are you sure you want to send the selected content item(s) to trash?</source>
```

2019-07-23 06:06 UTC, DominikaK commented on Resources/translations/sub_items.en.xliff
> +        <target state="new">Are you sure you want to send to the trash the selected content item(s)?</target>
```suggestion
        <target state="new">Are you sure you want to send the selected content item(s) to trash?</target>
```

2019-07-23 10:13 UTC, dew326 approved these changes

2019-07-26 08:24 UTC, lserwatka commented
This is candidate to 2.5.3 @barbaragr we need to merge it today if possible.

2019-07-26 08:25 UTC, barbaragr commented
@lserwatka sure, on my way 🚀

2019-07-26 09:28 UTC, dew326 approved these changes

2019-07-26 11:08 UTC, barbaragr approved these changes

2019-07-26 11:31 UTC, merged

2019-07-26 11:31 UTC, lserwatka commented
You can merge it up.

2019-07-26 11:35 UTC, tischsoic commented
Merged up:
- master: https://github.com/ezsystems/ezplatform-admin-ui-modules/commit/0f84f0a96aacc9df2828f7af089cf204f82d91e9