EZP-30320: Dispatch ez-content-tree-resized event on ContentTree resize
ezsystems/ezplatform-admin-ui-modules pull request #210
Opened 2019-09-10 11:14 UTC by tischsoic

JIRA: https://jira.ez.no/browse/EZP-30320

Related PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1083

2019-09-16 11:45 UTC, dew326 requested changes

2019-09-16 11:45 UTC, dew326 commented on src/modules/content-tree/components/content-tree/content.tree.js
> +        if (this.state.containerWidth != prevState.containerWidth) {
```suggestion
        if (this.state.containerWidth !== prevState.containerWidth) {
```

2019-10-30 10:33 UTC, dew326 approved these changes

2019-10-31 13:44 UTC, micszo approved these changes
Tested with https://github.com/ezsystems/ezplatform-admin-ui/pull/1083.

2019-11-12 08:00 UTC, micszo commented
@lserwatka this could be merged.

2019-11-12 10:49 UTC, merged