Added css to styling sub items
ezsystems/ezplatform-admin-ui-modules pull request #236
Opened 2019-12-11 13:07 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31185
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

Added css to sub items grid view

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2019-12-11 13:23 UTC, dew326 requested changes
The PR title and commit message is missing the ticket number, also the name is not very accurate. 
I would go for the ticket name or something like `Restyled grid view in sub-items`.

Also what about long content names? In the wireframe it has `...` after the second line.

2019-12-11 13:23 UTC, dew326 commented on Resources/public/scss/modules/sub-items-list/_grid.view.item.scss
> +    box-shadow: 0px calculateRem(2px) calculateRem(10px) calculateRem(-4px) rgba(0,0,0,0.15);
When it's `0` we don't use units

2019-12-11 13:23 UTC, dew326 commented on Resources/public/scss/modules/sub-items-list/_grid.view.item.scss
> +    border: 1px solid transparent;
`calculateRem(1px)`

2019-12-11 13:23 UTC, dew326 commented on Resources/public/scss/modules/sub-items-list/_grid.view.item.scss
> +        border: 1px solid $ez-secondary-ground;
`calculateRem(1px)`

2019-12-11 13:23 UTC, dew326 commented on Resources/public/scss/modules/sub-items-list/_grid.view.scss
> +        margin-right: calculateRem(35.75px);
This value is very big and strange. Could you explain why it has to be `35.75px`?

2019-12-12 09:14 UTC, dew326 commented on Resources/public/scss/modules/sub-items-list/_grid.view.item.scss
> +
```suggestion
```

2019-12-12 09:14 UTC, dew326 commented on Resources/public/scss/modules/sub-items-list/_grid.view.scss
> +        margin-right: calculateRem(36px);
As agreed in the private discussion we will change this to 20px

2019-12-12 10:19 UTC, dew326 approved these changes

2019-12-12 10:25 UTC, GrabowskiM approved these changes

2019-12-12 10:25 UTC, GrabowskiM commented on Resources/public/scss/modules/sub-items-list/_grid.view.item.scss
> +
Why empty line here?

2019-12-12 13:00 UTC, katarzynazawada requested changes
On Edge browser border is not visible when element is not focused 
![Screenshot 2019-12-12 at 13 59 07](https://user-images.githubusercontent.com/42930265/70714066-a76a3500-1ce7-11ea-932f-c796ad929caa.png)

2019-12-13 10:04 UTC, GrabowskiM approved these changes

2019-12-13 13:53 UTC, dew326 approved these changes

2019-12-13 13:56 UTC, GrabowskiM approved these changes

2019-12-13 14:17 UTC, katarzynazawada approved these changes
Looks good !

2019-12-13 14:18 UTC, merged