EZP-31215: Remove old UDW and deprecated code
ezsystems/ezplatform-admin-ui-modules pull request #237
Opened 2019-12-13 08:16 UTC by dew326

**Jira ticket:** https://jira.ez.no/browse/EZP-31215

2019-12-13 09:24 UTC, lserwatka approved these changes

2019-12-13 10:03 UTC, GrabowskiM requested changes

2019-12-13 10:03 UTC, GrabowskiM commented on src/modules/universal-discovery/components/grid-view/grid.view.item.js
> +                    iconExtraClasses={'ez-icon--extra-large'}
`iconExtraClasses="ez-icon--extra-large"`

2019-12-13 10:15 UTC, GrabowskiM approved these changes

2019-12-16 08:41 UTC, OstafinL approved these changes

2019-12-16 08:51 UTC, merged