EZP-29767: Added overflow to popup when it's partially hidden
ezsystems/ezplatform-admin-ui-modules pull request #245
Opened 2020-01-10 12:32 UTC by GrabowskiM

| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-29767
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no

Added and changed texts in relations fields.

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2020-01-10 12:39 UTC, dew326 approved these changes
Just small CS

2020-01-10 12:39 UTC, dew326 commented on src/modules/common/tooltip-popup/tooltip.popup.component.js
> +
```suggestion
```

2020-01-10 12:39 UTC, dew326 commented on src/modules/common/tooltip-popup/tooltip.popup.component.js
```suggestion
```

2020-01-13 09:53 UTC, OstafinL approved these changes

2020-01-14 12:51 UTC, katarzynazawada requested changes
React error occurs on Firefox when opening popup. http://g.recordit.co/QmH8NeTPp3.gif

2020-01-20 10:44 UTC, dew326 approved these changes

2020-01-20 10:45 UTC, OstafinL approved these changes

2020-01-20 13:07 UTC, katarzynazawada approved these changes

2020-01-20 15:27 UTC, merged