EZP-31256: Items list is not refreshed in new UDW when using content on the fly
ezsystems/ezplatform-admin-ui-modules pull request #247
Opened 2020-01-13 12:54 UTC by dew326

**Jira ticket:** https://jira.ez.no/browse/EZP-31256

2020-01-14 07:43 UTC, OstafinL approved these changes

2020-01-14 08:11 UTC, GrabowskiM approved these changes

2020-01-14 14:45 UTC, micszo requested changes
There's still an issue with refresh when the container has no sub-items.

2020-01-15 10:02 UTC, dew326 commented
@micszo fixed

2020-01-15 10:07 UTC, OstafinL approved these changes

2020-01-15 13:52 UTC, micszo approved these changes
QA Approved on eZ Platform EE master with branch.

2020-01-15 13:53 UTC, merged