EZP-31289: Create button is active before selecting location
ezsystems/ezplatform-admin-ui-modules pull request #248
Opened 2020-01-14 11:08 UTC by dew326

**Jira ticket:** https://jira.ez.no/browse/EZP-31289

2020-01-14 11:38 UTC, GrabowskiM approved these changes

2020-01-14 12:54 UTC, OstafinL approved these changes

2020-01-15 15:05 UTC, micszo requested changes
With this change behaviour is different in grid / tiles view.
When location is selected button doesn't become active.
Also in this view locations don't become marked (preview is not displayed) until they are double-clicked.

2020-01-16 11:45 UTC, dew326 commented
@micszo fixed

2020-01-17 09:54 UTC, micszo approved these changes
QA Approved on eZ Platform EE master with branch.

2020-01-17 09:55 UTC, merged