EZP-29157: Disabled MFU popup when UDW is open
ezsystems/ezplatform-admin-ui-modules pull request #255
Opened 2020-01-30 13:50 UTC by lucasOsti

Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31184
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2020-01-30 13:59 UTC, dew326 requested changes

2020-01-30 13:59 UTC, dew326 commented on src/modules/multi-file-upload/multi.file.upload.module.js
> +        window.document.body.addEventListener('ez-udw-closed', () => this.setState({ udwOpened: false }), false);
I think we should remove those listeners on unmount.

2020-01-30 14:33 UTC, GrabowskiM approved these changes

2020-01-30 14:33 UTC, GrabowskiM commented on src/modules/universal-discovery/universal.discovery.module.js
> +
not sure if this nw line is necessary

2020-01-30 14:37 UTC, dew326 approved these changes

2020-01-30 14:38 UTC, GrabowskiM approved these changes

2020-02-03 09:51 UTC, bogusez approved these changes

2020-02-03 10:05 UTC, merged

2020-02-03 10:06 UTC, lserwatka commented
Could you merge it up?