EZP-30909: Form created On the Fly should take full modal view
ezsystems/ezplatform-admin-ui-modules pull request #257
Opened 2020-01-31 08:30 UTC by GrabowskiM

| Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-30909
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no

Removed footer from form on the fly

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2020-01-31 10:23 UTC, dew326 requested changes

2020-01-31 10:23 UTC, dew326 commented on src/modules/universal-discovery/content.create.tab.module.js
> +        <div className={`m-content-create ${footerVisible ? 'm-content-create--footer-visible' : ''}`}>
We have helper `createCssClassNames` please use it

2020-01-31 10:23 UTC, dew326 commented on src/modules/universal-discovery/content.create.tab.module.js
> +
****
```suggestion
```

2020-01-31 10:25 UTC, OstafinL approved these changes

2020-01-31 11:27 UTC, dew326 commented on src/modules/universal-discovery/content.create.tab.module.js
> +    useEffect(() => {
```suggestion

    useEffect(() => {
```

2020-02-03 10:15 UTC, dew326 approved these changes

2020-02-04 10:15 UTC, tomaszszopinski approved these changes
QA Approved on eZ Platform EE v3 master with diff.

2020-02-04 10:15 UTC, merged