EZP-31343: Added sorting asc/desc to items of udw
ezsystems/ezplatform-admin-ui-modules pull request #258
Opened 2020-02-03 14:10 UTC by lucasOsti

Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31343
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2020-02-03 14:20 UTC, lucasOsti commented
![sorting](https://user-images.githubusercontent.com/24355391/73660524-a2e34c80-4698-11ea-8416-4e863b4fd5d6.png)
![sorting_revers](https://user-images.githubusercontent.com/24355391/73660529-a545a680-4698-11ea-9f7c-b0ca80e274bc.png)

2020-02-03 14:20 UTC, dew326 commented
ping @inakijv

2020-02-03 15:38 UTC, GrabowskiM requested changes

2020-02-03 15:38 UTC, GrabowskiM commented on Resources/public/scss/modules/universal-discovery/_sort.switcher.scss
> +            width: 0px;
px

2020-02-03 15:38 UTC, GrabowskiM commented on src/modules/universal-discovery/components/sort-switcher/sort.switcher.js
> +    const ascendingOrder = 'ascending';
personally I would move this kind of consts outside of component and write them in uppercase like `const ASCENDING_ORDER = 'ascending'` to distinct them from other variables, question for @dew326 what he thinks about it

2020-02-04 09:39 UTC, GrabowskiM requested changes

2020-02-04 09:39 UTC, GrabowskiM commented on Resources/public/scss/modules/universal-discovery/_sort.switcher.scss
> +
unnecessary empty line

2020-02-04 09:40 UTC, dew326 requested changes

2020-02-04 09:40 UTC, dew326 commented on src/modules/universal-discovery/components/sort-switcher/sort.switcher.js
> +
```suggestion
```

2020-02-04 10:04 UTC, dew326 commented
I'm not sure if the left padding in the button should be that big. For me it looks not ok, but this is question to @inakijv

2020-02-04 10:04 UTC, dew326 approved these changes

2020-02-04 12:38 UTC, GrabowskiM approved these changes

2020-02-04 15:11 UTC, inakijv commented
@dew326 I checked with @lucasOsti the different alternatives and his proposal is the most consistent with other sorting options we have in our UI.

2020-02-04 15:11 UTC, inakijv approved these changes

2020-02-05 08:53 UTC, bogusez approved these changes

2020-02-06 14:30 UTC, merged