EZP-30639: Used Content view instead of deprecated Location view
ezsystems/ezplatform-admin-ui-modules pull request #259
Opened 2020-02-05 09:18 UTC by Nattfarinn

2020-02-05 09:58 UTC, dew326 submitted a review, later dismissed

2020-02-05 10:01 UTC, ViniTou approved these changes

2020-02-05 12:57 UTC, dew326 requested changes

2020-02-05 12:57 UTC, dew326 commented on src/modules/sub-items/components/grid-view/grid.view.item.component.js
> +        <a className="c-grid-view-item" href={generateLink(content._info.id, locationId)}>
Order of parameters should be changed

2020-02-06 07:42 UTC, GrabowskiM approved these changes

2020-02-06 08:28 UTC, dew326 approved these changes

2020-02-10 13:20 UTC, OstafinL approved these changes

2020-02-27 13:58 UTC, merged