EZP-31355: When browsing in UDW children view is blocked by content meta preview
ezsystems/ezplatform-admin-ui-modules pull request #263
Opened 2020-02-07 10:58 UTC by dew326

**Jira ticket:** https://jira.ez.no/browse/EZP-31355

2020-02-07 12:21 UTC, GrabowskiM requested changes

2020-02-07 12:21 UTC, GrabowskiM commented on src/modules/universal-discovery/components/finder/finder.js
> +        if (!container) {
Is this if needed? useEffect is called each time after page is rendered, so this `<div>` will be always created.

2020-02-10 08:06 UTC, GrabowskiM approved these changes

2020-02-10 13:19 UTC, OstafinL approved these changes

2020-02-13 10:37 UTC, tomaszszopinski approved these changes
QA Approved on eZ Platform OSS v3.0 master & eZ Platform EE v3.0 master with diff. Travis failure unrelated.

2020-02-13 10:43 UTC, lserwatka commented
@dew326 could you rebase?

2020-02-13 10:46 UTC, dew326 commented
@lserwatka done

2020-02-13 10:47 UTC, merged