EZP-31345 Added language select when user edit sub items
ezsystems/ezplatform-admin-ui-modules pull request #270
Opened 2020-02-17 12:16 UTC by lucasOsti

Question      | Answer
| ------------- | ---
| Tickets       | https://jira.ez.no/browse/EZP-31345
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2020-02-18 11:23 UTC, GrabowskiM requested changes

2020-02-18 11:23 UTC, GrabowskiM commented on src/modules/sub-items/components/sub-items-list/instant.filter.component.js
> +        const itemsMap = items.reduce(
Why `reduce` instead of simply `map`?

2020-02-18 11:23 UTC, GrabowskiM commented on src/modules/sub-items/components/sub-items-list/instant.filter.component.js
> +        window.clearTimeout(filterTimeout);
`clearTimeout` should go to return function insteaed of here
```suggestion
      useEffect(() => {
        const filterActionTimeout = window.setTimeout(() => {
            const results = itemsMap.filter((item) => item.label.includes(filterQuery.toLowerCase()));

            itemsMap.forEach((item) => item.element.setAttribute('hidden', true));
            results.forEach((item) => item.element.removeAttribute('hidden'));
        }, FILTER_TIMEOUT);

        return () => {
          window.clearTimeout(filterActionTimeout);
        }
    }, [filterQuery]);
```

2020-02-18 11:23 UTC, GrabowskiM commented on src/modules/sub-items/components/sub-items-list/instant.filter.component.js
> +            const results = itemsMap.filter((item) => item.label.includes(filterQuery.toLowerCase()));
You can store `filterQuery.toLowerCase()` in new variable so that you won't fire toLowerCase with each filter iteration

2020-02-18 11:23 UTC, GrabowskiM commented on src/modules/sub-items/components/sub-items-list/instant.filter.component.js
> +                                    onChange={(event) => props.handleItemChange(event)}
Could be just `onChange={props.handleItemChange}`

2020-02-18 11:23 UTC, GrabowskiM commented on src/modules/sub-items/components/table-view/table.view.item.component.js
> +        const languageItems = languageCodes.reduce(
Why `reduce` instead of simply `map`?

2020-02-18 11:23 UTC, GrabowskiM commented on src/modules/sub-items/components/table-view/table.view.item.component.js
> +        } else {
Unnecessary else
```suggestion
        }
        return false;
      }
    }
```

2020-02-18 11:23 UTC, GrabowskiM commented on src/modules/sub-items/sub.items.module.js
> +        const rightMainMenuNode = document.querySelector(RIGHT_MAIN_MENU_SELECTOR);
Could go inside if

2020-02-18 14:58 UTC, GrabowskiM commented on src/modules/sub-items/components/table-view/table.view.item.component.js
> +        const languageItems = languageCodes.reduce(
```suggestion
        const languageItems = languageCodes.map((item) => ({ 
                    label: languages[item].name,
                    value: item,
        }));
```

2020-02-19 09:50 UTC, dew326 requested changes
Review discussed in private, some changes in the architecture are needed

2020-02-19 15:09 UTC, GrabowskiM approved these changes

2020-02-20 08:13 UTC, dew326 requested changes

2020-02-20 08:13 UTC, dew326 commented on Resources/public/scss/modules/sub-items-list/_language.selector.scss
> +
```suggestion
```

2020-02-20 08:13 UTC, dew326 commented on src/modules/sub-items/components/sub-items-list/instant.filter.component.js
> +
```suggestion
```

2020-02-20 08:13 UTC, dew326 commented on src/modules/sub-items/components/sub-items-list/instant.filter.component.js
> +                item.element[methodName]('hidden', true);
```suggestion

                item.element[methodName]('hidden', true);
```

2020-02-20 08:13 UTC, dew326 commented on src/modules/sub-items/components/sub-items-list/instant.filter.component.js
> +    uniqueId: PropTypes.string,
I think this is not needed anymore. I current implementation there will be only one `InstantFilter` and it will always be the same value.

2020-02-20 08:13 UTC, dew326 commented on src/modules/sub-items/components/sub-items-list/instant.filter.component.js
> +    itemClass: PropTypes.string,
Is this have to be in prop? It can be just regular variable. I don't see a point of overriding this by parent component, or am I missing something.

2020-02-20 08:13 UTC, dew326 commented on src/modules/sub-items/components/sub-items-list/language.selector.compoment.js
> +        'ez-language-selector': true,
```suggestion
        'c-language-selector': true,
```

2020-02-20 08:13 UTC, dew326 commented on src/modules/sub-items/components/table-view/table.view.component.js
> +     * Set language selector data
```suggestion
     * Sets language selector data
```

2020-02-20 14:42 UTC, dew326 commented on src/modules/sub-items/components/sub-items-list/instant.filter.component.js
> +                    placeholder="Type to refine"
I think we need translation

2020-02-20 14:58 UTC, dew326 approved these changes

2020-02-21 08:14 UTC, dew326 approved these changes

2020-02-21 12:39 UTC, bogusez commented
I've got a problem with editting sub-items after cloning this. You can find more info on attached screenshot below.
![Screenshot 2020-02-21 at 13 31 04](https://user-images.githubusercontent.com/59828795/75035324-81af9800-54af-11ea-9c76-fd7599170c52.png)

2020-02-24 09:52 UTC, bogusez approved these changes

2020-02-24 09:53 UTC, merged