EZP-31680: Added UDW Search language filter
ezsystems/ezplatform-admin-ui-modules pull request #286
Opened 2020-06-09 14:47 UTC by barw4

Jira ticket: https://jira.ez.no/browse/EZP-31680

![image](https://user-images.githubusercontent.com/22300504/84162688-f1eb2500-aa70-11ea-92cb-f9429c2a364b.png)

2020-06-10 05:41 UTC, dew326 requested changes

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/components/search/search.component.js
> +        const language = this._refSearchLanguage.value;
```suggestion
        const languageCode = this._refSearchLanguage.value;
```

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/components/search/search.component.js
> +                    this.props.findContentBySearchQuery(this.props.restInfo, query, resolve, this.props.searchResultsLimit, language)
```suggestion
                    this.props.findContentBySearchQuery(this.props.restInfo, query, resolve, this.props.searchResultsLimit, languageCode)
```

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/components/search/search.component.js
> +
```suggestion
```

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/components/search/search.component.js
> +        const { languages } = this.props;
Please move this to the top of the method. Destructs of `state` or `props` should be on the top.

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/components/search/search.component.js
> +
```suggestion
```

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/components/search/search.component.js
> +            return <option value={language.languageCode}>{language.name}</option>;
```suggestion

            return <option value={language.languageCode}>{language.name}</option>;
```

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/components/search/search.component.js
> +            <div className="c-search-language__select-wrapper">
This is not proper BEM usage
```suggestion
            <div className="c-search__language-wrapper">
```

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/components/search/search.component.js
> +
```suggestion

```

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/components/search/search.component.js
> +        const { languages } = this.props;
You should also add `languages` to the `propTypes`

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/services/universal.discovery.service.js
> +            languageCode: languageCode,
```suggestion
            languageCode,
```

2020-06-10 05:41 UTC, dew326 commented on src/modules/universal-discovery/universal.discovery.module.js
> +        const searchPanelConfig = {
I think Prettier will make it one line.
Please use Prettier.

2020-06-10 08:40 UTC, barw4 commented
@dew326 resolved in https://github.com/ezsystems/ezplatform-admin-ui-modules/pull/286/commits/6787ebbf3bd09f3b471a2fd7574733021e7978b0

2020-06-10 10:18 UTC, dew326 approved these changes
Could you also create a PR for new UDW in ezplatform-admin-ui?

2020-06-10 10:28 UTC, barw4 commented
> Could you also create a PR for new UDW in ezplatform-admin-ui?

@dew326 yes, I'll do it after approval of related kernel PR, just to be sure everything is fine.

2020-06-15 08:23 UTC, GrabowskiM approved these changes

2020-06-19 13:17 UTC, merged