EZP-31602: Moving to trash confirmation modal is not updated after su…
ezsystems/ezplatform-admin-ui-modules pull request #289
Opened 2021-04-26 11:55 UTC by lucasOsti

| Question      | Answer
| ------------- | ---
| Tickets       | https://issues.ibexa.co/browse/EZP-31602
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | no
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ezsystems/ezplatform-admin-ui/blob/master/LICENSE)

#### Checklist:
- [x] Coding standards (`$ composer fix-cs`)
- [x] Ready for Code Review

2021-04-27 06:23 UTC, dew326 requested changes

2021-04-27 06:23 UTC, dew326 commented on src/modules/sub-items/sub.items.module.js
> +        this.updateTrashModal();
Not sure it this should be fired every time when React is rerendering the list view

2021-04-28 08:16 UTC, tischsoic requested changes

2021-04-28 08:16 UTC, tischsoic commented on src/modules/sub-items/sub.items.module.js
> +        this.updateTrashModal();
Probably should be also added in `afterBulkDelete` method.

2021-04-28 09:22 UTC, tischsoic approved these changes

2021-04-28 12:42 UTC, GrabowskiM approved these changes

2021-04-29 06:13 UTC, dew326 approved these changes

2021-05-05 11:06 UTC, kacper-wieczorek-ibexa approved these changes
QA Approve - tested on 2.5
Tests on v3 after merge-up

2021-05-05 11:10 UTC, lserwatka commented
@mnocon is it safe to merge it?

2021-05-05 11:17 UTC, mnocon commented
@lserwatka the tests here failed because at that time there was an issue in kernel (now fixed in https://github.com/ezsystems/ezpublish-kernel/pull/3097), same for https://github.com/ezsystems/ezplatform-admin-ui/pull/1744

I've restarted both jobs, but I expect both of them to be green

2021-05-05 11:18 UTC, lserwatka commented
Sounds great, thank you for checking @mnocon 👍

2021-05-05 14:06 UTC, merged

2021-05-05 14:06 UTC, lserwatka commented
You can merge it up.