[EZP-28729] Missing tooltips for multifile upload and switch view
ezsystems/ezplatform-admin-ui-modules pull request #48
Opened 2018-01-23 12:11 UTC by ViniTou

https://jira.ez.no/browse/EZP-28729

2018-01-23 12:56 UTC, webhdx requested changes

2018-01-23 12:56 UTC, webhdx commented on src/modules/multi-file-upload/multi.file.upload.module.js
> +                <svg className="ez-icon">extractDroppedFilesList(2)
??

2018-01-24 07:40 UTC, ViniTou commented on src/modules/multi-file-upload/multi.file.upload.module.js
> +                <svg className="ez-icon">extractDroppedFilesList(2)
Confused about this as much as you are.

2018-01-24 13:32 UTC, dew326 requested changes
Permissions on files are changed from 644 to 755, please restore 644.

2018-01-24 13:32 UTC, dew326 commented on src/modules/sub-items/components/view-switcher/view.switcher.component.js
> +};
missing empty line in the end of file

2018-01-24 13:35 UTC, barbaragr approved these changes
Tooltips works fine for:
1. Dashboard/Edit button
2. Sub-items/Multifile upload
3. Sub-items/switcher list view/tab view

2018-01-24 14:09 UTC, dew326 commented on src/modules/sub-items/components/view-switcher/view.switcher.component.js
> +            title: this.props.tooltipLabel
I think it would be better to have a tooltip on each button ('List view', 'Grid view') instead of one 'Change view'.

2018-01-25 10:16 UTC, barbaragr approved these changes

2018-01-25 12:22 UTC, dew326 approved these changes

2018-01-25 12:26 UTC, sunpietro requested changes

2018-01-25 12:26 UTC, sunpietro commented on src/modules/sub-items/components/view-switcher/view.switcher.component.js
> +        const attrs = {
IT's not needed. Please, revert the previous version.

2018-01-25 12:26 UTC, sunpietro commented on src/modules/sub-items/components/view-switcher/view.switcher.component.js
> +    renderButton(id, icon, titleLabel) {
`title` instead of `titleLabel`

2018-01-25 12:26 UTC, sunpietro commented on src/modules/sub-items/components/view-switcher/view.switcher.component.js
> +            title: titleLabel
just `title` (without assignment)

2018-01-25 12:26 UTC, sunpietro commented on src/modules/sub-items/components/view-switcher/view.switcher.component.js
> +        title: PropTypes.object.isRequired
The `labels` object should be as flat as possible, so `listViewTitle` and `gridViewTitle` are ok. No need to nest the `title` sub-object.

2018-01-25 12:26 UTC, sunpietro commented on src/modules/sub-items/components/view-switcher/view.switcher.component.js
> +        title: {
Please, apply changes according to the comment above.

2018-01-25 13:12 UTC, sunpietro approved these changes

2018-01-25 13:12 UTC, merged