EZP-29270: Sub-items sorting order not respected by UDW
ezsystems/ezplatform-admin-ui-modules pull request #72
Opened 2018-06-21 11:14 UTC by tischsoic

https://jira.ez.no/browse/EZP-29270

2018-06-21 11:41 UTC, dew326 requested changes
I don't like the approach. You are creating clauses map based on fetched locations (it's 50 locations but it can be changed by integrator). This could be done in a simpler way. Just create one sortClauses just before `findLocationsByParentLocationId()` you have all information there. It's too many calculations on each load.

2018-06-22 07:24 UTC, dew326 requested changes

2018-06-22 07:24 UTC, dew326 commented on src/modules/universal-discovery/components/finder/finder.component.js
> +    onLoadMore(parentLocation) {
Potential BC break, you can add new parameter but you cannot change the existing one.

2018-06-22 07:28 UTC, lserwatka commented on src/modules/universal-discovery/components/finder/finder.component.js
> +    onLoadMore(parentLocation) {
Is this a public method or API?

2018-06-22 07:29 UTC, sunpietro reviewed
It's not public.

2018-06-22 07:29 UTC, sunpietro commented on src/modules/universal-discovery/components/finder/finder.component.js
> +    sortFieldMappings: PropTypes.object,
Shouldn't it be required?

2018-06-22 07:29 UTC, sunpietro commented on src/modules/universal-discovery/components/finder/finder.component.js
> +    onLoadMore(parentLocation) {
It's not public method. The public API is about existing extension points. This method is not one of them

2018-06-22 07:30 UTC, lserwatka commented on src/modules/universal-discovery/components/finder/finder.component.js
> +    onLoadMore(parentLocation) {
OK, so we should be fine.

2018-06-22 07:55 UTC, tischsoic commented on src/modules/universal-discovery/components/finder/finder.component.js
> +    sortFieldMappings: PropTypes.object,
Good point.

2018-06-22 12:52 UTC, sunpietro approved these changes

2018-06-22 12:56 UTC, dew326 approved these changes

2018-06-22 13:17 UTC, barbaragr approved these changes

2018-06-22 13:17 UTC, merged